{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d30180b2-af2e-4e84-85ab-50f5f60a064f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10 Business Queries created successfully!\n"
     ]
    }
   ],
   "source": [
    "sql_queries = \"\"\"\n",
    "\n",
    "-- Q1: Top 5 Products by Total Sales\n",
    "SELECT\n",
    "    \"Product Name\",\n",
    "    SUM(Sales) AS Total_Sales\n",
    "FROM sales\n",
    "GROUP BY \"Product Name\"\n",
    "ORDER BY Total_Sales DESC\n",
    "LIMIT 5;\n",
    "\n",
    "\n",
    "-- Q2: Monthly Sales Trend\n",
    "SELECT\n",
    "    strftime('%Y-%m', \"Order Date\") AS Month,\n",
    "    SUM(Sales) AS Total_Sales\n",
    "FROM sales\n",
    "GROUP BY Month\n",
    "ORDER BY Month;\n",
    "\n",
    "\n",
    "-- Q3: Customer Segmentation by Total Spend\n",
    "SELECT\n",
    "    \"Customer Name\",\n",
    "    SUM(Sales) AS Total_Spend\n",
    "FROM sales\n",
    "GROUP BY \"Customer Name\"\n",
    "ORDER BY Total_Spend DESC\n",
    "LIMIT 10;\n",
    "\n",
    "\n",
    "-- Q4: Most Profitable Region\n",
    "SELECT\n",
    "    Region,\n",
    "    SUM(Profit) AS Total_Profit\n",
    "FROM sales\n",
    "GROUP BY Region\n",
    "ORDER BY Total_Profit DESC;\n",
    "\n",
    "\n",
    "-- Q5: Average Discount by Category\n",
    "SELECT\n",
    "    Category,\n",
    "    ROUND(AVG(Discount), 2) AS Average_Discount\n",
    "FROM sales\n",
    "GROUP BY Category;\n",
    "\n",
    "\n",
    "-- Q6: Sales and Profit by Category\n",
    "SELECT\n",
    "    Category,\n",
    "    SUM(Sales) AS Total_Sales,\n",
    "    SUM(Profit) AS Total_Profit\n",
    "FROM sales\n",
    "GROUP BY Category\n",
    "ORDER BY Total_Sales DESC;\n",
    "\n",
    "\n",
    "-- Q7: Top 10 States by Sales\n",
    "SELECT\n",
    "    State,\n",
    "    SUM(Sales) AS Total_Sales\n",
    "FROM sales\n",
    "GROUP BY State\n",
    "ORDER BY Total_Sales DESC\n",
    "LIMIT 10;\n",
    "\n",
    "\n",
    "-- Q8: Sales by Ship Mode\n",
    "SELECT\n",
    "    \"Ship Mode\",\n",
    "    COUNT(*) AS Total_Orders,\n",
    "    SUM(Sales) AS Total_Sales\n",
    "FROM sales\n",
    "GROUP BY \"Ship Mode\"\n",
    "ORDER BY Total_Orders DESC;\n",
    "\n",
    "\n",
    "-- Q9: Yearly Sales\n",
    "SELECT\n",
    "    strftime('%Y', \"Order Date\") AS Year,\n",
    "    SUM(Sales) AS Total_Sales\n",
    "FROM sales\n",
    "GROUP BY Year\n",
    "ORDER BY Year;\n",
    "\n",
    "\n",
    "-- Q10: Year-over-Year Sales Growth\n",
    "WITH yearly_sales AS (\n",
    "    SELECT\n",
    "        strftime('%Y', \"Order Date\") AS year,\n",
    "        SUM(Sales) AS total_sales\n",
    "    FROM sales\n",
    "    GROUP BY year\n",
    ")\n",
    "SELECT\n",
    "    year,\n",
    "    total_sales,\n",
    "    LAG(total_sales) OVER (ORDER BY year) AS prev_year_sales,\n",
    "    ROUND(\n",
    "        (total_sales - LAG(total_sales) OVER (ORDER BY year))\n",
    "        / LAG(total_sales) OVER (ORDER BY year) * 100,\n",
    "        2\n",
    "    ) AS growth_pct\n",
    "FROM yearly_sales\n",
    "ORDER BY year;\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "print(\"10 Business Queries created successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "32ccd0f4-1945-4e27-ad4e-d05c8c9d56b7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
